### ISSUE TITLE
is this code working fine??

### ISSUE THREAD

**Issue by hvs42** [radhay-1199/vaccinenotifier#1]

**Comment by radhay-1199** [comment]
Yes

**Comment by radhay-1199** [comment]
Yes completely tested

**Comment by hvs42** [comment]
One thing I want to ask, in this program if there is any available seat than it sends mail, but it kept mailing till it is available, Is there any function you have created to tackle this problem.

I am facing the same issue. Is there any way to control this.

**Comment by radhay-1199** [comment]
The solution i came up for this was to stop my pm2 process once i get email for next 10 days vaccine availability. I used pm2 api for stoppping the services. You can read more about them here : https://pm2.keymetrics.io/docs/usage/pm2-api/
